;(function($,_,undefined){"use strict";ips.controller.register('plugins.bimGiphy',{_timer:null,_ajax:null,_value:'',_type:'gifs',initialize:function(){this.on('click','[data-action="playGif"]',this.playGif);this.on('click','[data-action="selectGif"]',this.insertGif);this.on('focus','[data-role="gifSearch"]',this.focusGifSearch);this.on('blur','[data-role="gifSearch"]',this.blurGifSearch);this.on('change','[data-role="gifType"]',this._checkValue);this.on('paginationClicked paginationJump',this.paginationClicked);},playGif:function(e){var container=$(e.currentTarget).prev();var bg=container.css('background-image');bg=bg.replace('url(','').replace(')','').replace(/\"/gi,"");var gif=container.attr('data-preview');if(bg!=gif){container.css('background-image','url('+gif+')');console.log("Playing GIF");}},insertGif:function(e){var element=$(e.currentTarget).attr('class');var id=$(e.currentTarget).attr('data-gifid');var gif=$(e.currentTarget).attr('data-original');var title=$(e.currentTarget).closest('.giphyIMG').attr('title');var original=$(e.currentTarget).attr('data-original');var preview_gif=$(e.currentTarget).attr('data-preview');var still=$(e.currentTarget).attr('data-still');var eID=$(this.scope).data('editorid');if(eID.toLowerCase().indexOf("chatbox_")==0&&eID.toLowerCase().indexOf("chatbox_content_ajax")<0){var evar=eID.split("_");var cbWrapper=evar[1]=='room'?$('.room_'+evar[2]):$('.convo_'+evar[2]);cbWrapper.find('textarea').val(gif).closest('form').submit();}
else if(eID=='chatbox'){var input=$('[data-controller="bim.chatbox.free"]').find('input');input.val(gif);input.closest('form').click();}
else if(eID=='giphyCMD'){var mediaBox=this.scope.closest('.chatboxMedia');mediaBox.empty().hide();var input=mediaBox.next().find('textarea').length>0?mediaBox.next().find('textarea'):mediaBox.next().find('.bimcb_chatInput');input.val(gif).submit();}
else
{var editor=CKEDITOR.instances[eID];if(ips.getSetting('bim_giphy_play')==1){editor.insertHtml('<img alt="'+title+'" class="ipsImage bimGiphyIMG" src="'+gif+'">');}
else
{var element=CKEDITOR.dom.element.createFromHtml('<div class="bimGiphyContainer" contenteditable="false"></div>');element.setHtml('<img alt="'+title+'" class="ipsImage bimGiphyIMG" src="'+still+'"><div class="giphyPlayBtn"></div>');element.isEditable=false;editor.insertElement(element);editor.widgets.initOn(element,'bimGiphyContainer');$(document).trigger('contentChange',[$(element.$)]);}}
var item={'id':id,'title':title,'images':{'original':{'url':original},'preview_gif':{'url':preview_gif},'original_still':{'url':still}}};var existing=ips.utils.db.get('bimgiphy_gif','recent');if(!existing||!_.isArray(existing)){var json=[item];ips.utils.db.set('bimgiphy_gif','recent',json);}
else
{for(var key in existing){var obj=existing[key];if(obj.id==item.id){this.trigger('closeDialog');return;}}
existing.unshift(item);if(existing.length>12){existing.splice((existing.length-12)*-1,existing.length-12);}
ips.utils.db.set('bimgiphy_gif','recent',existing);}
this.trigger('closeDialog');},paginationClicked:function(e,data){var self=this;var results=this.scope.find('[data-role="gifResults"]');var url=data.href;data.originalEvent.preventDefault();if(url=='#'){url=data.paginationElem.find('[data-role="pageJump"]').attr('action')+'&page='+data.pageNo;}
this._ajax=ips.getAjax()(url,{showLoading:true,data:{q:this._value,type:this._type,}}).done(function(response){results.html(response);$(document).trigger('contentChange',[results]);});},focusGifSearch:function(){this._timer=setInterval(_.bind(this._checkValue,this),700);},blurGifSearch:function(){clearInterval(this._timer);},_checkValue:function(){var value=this.scope.find('[data-role="gifSearch"]').val();var type=this.scope.find('[data-role="gifType"]').val();if(value==this._value&&type==this._type){return;}
this._value=value;this._type=type;this._loadResults();},_loadResults:function(){var self=this;var url=this.scope.attr('data-url');var recent=ips.utils.db.get('bimgiphy_gif','recent');var recentData=null;if(!this._value){if(_.isArray(recent)){recentData=JSON.stringify(recent);}}
if(this._ajax&&this._ajax.abort){this._ajax.abort();}
this.scope.find('[data-role="gifSearch"]').addClass('ipsField_loading');this._ajax=ips.getAjax()(url,{data:{q:this._value,type:this._type,offset:0,recent:recentData},type:'post',}).done(function(response){self.scope.find('[data-role="gifResults"]').html(response);$(document).trigger('contentChange',[self.scope.find('[data-role="gifResults"]')]);}).always(function(){self.scope.find('[data-role="gifSearch"]').removeClass('ipsField_loading');});}});}(jQuery,_));$(document).ready(function(){$(document).on('click touchend','.giphyPlayBtn',function(e){var container=$(this).closest('.bimGiphyContainer');var img=container.find('.bimGiphyIMG');var gifURL=img.attr('src').replace("giphy_s.gif","giphy.gif");if($(this).closest('.cke_inner').length<=0){img.attr('src',gifURL);$(this).hide();}
else
{var gifID="giphy_"+makeid();container.addClass(gifID);var div=$("<div />",{html:"<style>.cke_inner ."+gifID+" .giphyPlayBtn, .cke_inner ."+gifID+" .ipsImage { visibility: hidden; } .cke_inner ."+gifID+" { background-image: url('"+gifURL+"') }</style>"}).appendTo("body");}
return false;});function makeid(){var text="";var possible="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(var i=0;i<5;i++)
text+=possible.charAt(Math.floor(Math.random()*possible.length));return text;}});;